from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Web(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ShopName = db.Column(db.String(100))
    ShopRating = db.Column(db.Float)
    Category_catchtable = db.Column(db.String(100))
    Location_catchtable = db.Column(db.String(100))
    LunchDinner = db.Column(db.String(50))
    Description = db.Column(db.Text)
    Reviews = db.Column(db.Integer)
    Address = db.Column(db.String(200))
    Nickname = db.Column(db.String(100))
    User_Rating = db.Column(db.Float)
    MealTime = db.Column(db.String(50))
    Date = db.Column(db.String(50))
    User_Review = db.Column(db.Text)
    Save = db.Column(db.Float)
    Category_catchtable_1 = db.Column(db.String(100))
    avg_점심 = db.Column(db.String(100))
    avg_저녁 = db.Column(db.String(100))
    min_점심 = db.Column(db.Float)
    max_점심 = db.Column(db.Float)
    min_저녁 = db.Column(db.Float)
    max_저녁 = db.Column(db.Float)
    Location = db.Column(db.String(20))
    Lunch = db.Column(db.String(50))
    Dinner = db.Column(db.String(50))
