"""migration

Revision ID: 8c54571264c6
Revises: 
Create Date: 2024-07-16 18:02:45.158360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c54571264c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.alter_column('ShopName',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('Category_catchtable',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('Location_catchtable',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('LunchDinner',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('Description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('Address',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('Nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('MealTime',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('Date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('User_Review',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('Save',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('Category_catchtable_1',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('avg_점심',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100),
               ullable=True)
        batch_op.alter_column('avg_저녁',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('min_점심',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('max_점심',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('min_저녁',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('max_저녁',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('Location',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('Lunch',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('Dinner',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.alter_column('Dinner',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Lunch',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Location',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('max_저녁',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('min_저녁',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('max_점심',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('min_점심',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('avg_저녁',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('avg_점심',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('Category_catchtable_1',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Save',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('User_Review',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('Date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('MealTime',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('Nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Address',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('LunchDinner',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Location_catchtable',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Category_catchtable',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ShopName',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
